### PR TITLE
Graveyard 2

### PR DESCRIPTION
**Pull request by nnamdiarimah**
The current Graveyard page only works for desktop
Screen Shot 2022-01-23 at 6 31 12 PM
Currently on mobile:
Screen Shot 2022-01-23 at 6 31 41 PM
Can you add a dropdown similar to how is done on opensea? The text gets too long on mobile:
Screen Shot 2022-01-23 at 6 32 51 PM

- We'll also need help making the collection and nft sections scale properly on mobile

### CODE REVIEW

**Comment by aubundy** [comment]
@nnamss Can I change the Collections filter selection to be a list of tabs side-by-side like OpenSea? The current layout makes it so a user has to scroll through a list of cards in order to filter the NFTs, and it's even more tedious on mobile where the cards are around 70% of screen height.

Screenshot 2022-01-26 232036

**Comment by nnamdiarimah** [comment]
Sure!

**Comment by aubundy** [comment]
@nnamss just pushed graveyard updates for mobile

**Comment by nnamdiarimah** [comment]
@aubundy awesome thanks 👌🏾

**Pull request closed without merging**
